name: Echo Hello World

on:
  push:
    branches:
      - main
      - master

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World"
name: Hello then Hi Jana

on:
  push:
    branches:
      - main
      - master

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello World"

  hi-jana:
    needs: hello-world
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hi Jana
        run: echo "Hi Jana"
